version: "3"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "./dev_start.sh"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /ziv/shared/rule:/ziv/shared/rule
      - /ziv/shared/packages:/ziv/shared/packages
    depends_on:
      - redis

  redis:
    image: "redis:latest"
