version: "3"

services:
  app:
    build:
      context: ./backend
      dockerfile: dockerfile
    command: "./scripts/dev_start.sh"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/config_files/clamd.conf:/etc/clamav/clamd.conf
      - /ziv/shared/rule:/ziv/shared/rule
      - /ziv/shared/packages:/ziv/shared/packages
      - /ziv/shared/scandir:/scandir
      - /var/lib/docker/data/clamav/sockets/:/run/clamav
    depends_on:
      - clamav
    networks:
      - clamav_network

  clamav:
    image: "clamav/clamav:stable"
    volumes:
      - clam_db:/var/lib/clamav
      - ./backend/config_files/clamd.conf:/etc/clamav/clamd.conf
      - /var/lib/docker/data/clamav/sockets/:/run/clamav
      - /ziv/shared/scandir:/scandir
    networks:
      - clamav_network
    command: bash -c "chown -R clamav:clamav /run/clamav && clamd"

volumes:
  clam_db:

networks:
  clamav_network: {}
