version: "3"

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: "./dev_start.sh"
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - /ziv/shared/rule:/ziv/shared/rule
    depends_on:
      - redis

  redis:
    image: "redis:latest"
