version: "3"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "./scripts/dev_start.sh"
    ports:
      - "3888:8000"
    volumes:
      - ./backend:/app
      - ./backend/config_files/clamd.conf:/etc/clamav/clamd.conf
      - /ziv/shared/rule:/ziv/shared/rule
      - /ziv/shared/packages:/ziv/shared/packages
      - /ziv/shared/scandir:/scandir
      - /var/lib/docker/data/clamav/sockets/:/run/clamav
    depends_on:
      - clamav
    networks:
      - clamav_network

  clamav:
    image: "file-upload-app"
    platform: linux/arm64
    volumes:
      - clam_db:/var/lib/clamav
      - ./backend/config_files/clamd.conf:/etc/clamav/clamd.conf
      - /var/lib/docker/data/clamav/sockets/:/run/clamav
      - /ziv/shared/scandir:/scandir
    env_file:
      - ./backend/clamav.env
    networks:
      - clamav_network
    command: bash -c "chown -R clamav:clamav /var/lib/clamav /run/clamav && freshclam && exec clamd --foreground --config-file=/etc/clamav/clamd.conf"

volumes:
  clam_db:

networks:
  clamav_network: {}
