# Collection -------------------------------------------------------------------
repo_staging_dir: "/ziv/shared/rule"

fetched_rule_dir: "/ziv/shared/packages"

yara_repositories:
  - name: "Project"
    url: "https://github.com/Yara-Rules/rules"
    author: "yara"
    branch: "master"
